### ISSUE TITLE
Could not find required file index.hml

### ISSUE THREAD

**Issue by tyler-austin** [ralberth/quizshow#1]
Executing the command `npm start` results in the following error:

![Screen Shot 2019-08-03 at 4 01 24 PM](https://user-images.githubusercontent.com/12815393/62416396-087e4f80-b608-11e9-9e68-5a86363c0924.png)

**Comment by ralberth** [comment]
Awesome!  You're using it!  I have a big commit coming this weekend.    I dropped Gatsby for CRA, it's a single-page app now and I'm switching out the home page just a little.  Hold on until tomorrow...

**Comment by ralberth** [comment]
Fixed with commit e9fddae57589ab72683c3c2d8f2a1574d2fc8fa6
